#ifndef __LIBONI_DRIVER_XILLYBUS_H__
#define __LIBONI_DRIVER_XILLYBUS_H__

// Driver options
enum  {
    ONI_XILLYBUS_CONFIGSTREAMPATH,
    ONI_XILLYBUS_SIGNALSTREAMPATH,
    ONI_XILLYBUS_READSTREAMPATH,
    ONI_XILLYBUS_WRITESTREAMPATH
};

#define XILLYBUS_DRIVER_NAME "xillybus"

#endif
