#ifndef __LIBONI_DRIVER_OEPCIE_H__
#define __LIBONI_DRIVER_OEPCIE_H__

// Driver options
enum  {
    ONI_OEPCIE_CONFIGSTREAMPATH,
    ONI_OEPCIE_READSTREAMPATH,
    ONI_OEPCIE_WRITESTREAMPATH,
    ONI_OEPCIE_SIGNALSTREAMPATH
};

#define OEPCIE_NAME "oepcie"

#endif
